### ISSUE TITLE
Implement REST API for figuring out where the event attendees are

### ISSUE THREAD

**Issue by chrisjeon** [ninaqyang/locatr-rails#4]
Thinking about it now, this can just use the participants table, which is already a join table. Should just have to add latitude and longitude to participants table.

**Comment by jesuiswk** [comment]
Just notice this.  Possible to remove it from issue list? 

_Sent from my HONOR FRD-L04 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
